In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import re

In [2]:
#Cambiar la estrucutra para las ids, tengo que usar las url para las series y con eso sacar los map id 
#Problemas con el event desde que hice el cambio a lower para automatizar en la creacion de torneos, los ":"
#son el mayor de los quilombos. En teoria es una columna alpedo, eso deberia ser el otro paso de optimizacion 
#Agregar tabla de rondas y que significa (r1, 1-1, etc )
#REVISAR EL PROBLEMA CON LOS EQUIPOS CHINOS QUE NO TIENE ECONOMIA Y ME ROMPE LAS TABLAS

In [3]:
def convert_k(valor):
    "remove k in money columns and change the format to int"
    try:
        if type(valor) == str:
            if 'k' in valor:
                return int(float(valor.replace('k', '')) * 1000)
        else:
            return int(valor)

    except:
        return int(valor)

def find_files_by_prefix(root_folder, prefix):
    matched_files = []
    for dirpath, _, filenames in os.walk(root_folder):
        for file in filenames:
            if file.startswith(prefix):
                full_path = os.path.join(dirpath, file)
                matched_files.append(full_path)
    return matched_files

def concat_from_list(file_list,encoding='iso-8859-1'):
    dataframes = []
    for file in file_list:
        try:
            df = pd.read_csv(file,encoding=encoding)
            if not df.empty:
                dataframes.append(df)
            else:
                print(f"empty file: {file}")
        except Exception as e:
            print(f"Error reading {file}: {e}")
    
    if dataframes:
        return pd.concat(dataframes, ignore_index=True)
    else:
        print("Load file fail")
        return pd.DataFrame()

def concat_csv_from_different_folders(folder="csv",prefix=None):
    if prefix is None:
        print("Add a prefix")

    file_list = find_files_by_prefix(root_folder=folder,prefix=prefix)
    df_concat = concat_from_list(file_list)
    return df_concat

# def get_game_instance(value):
#     last_char = value.split("-")[-1]
#     return last_char

def text_to_index(df,name,number=0,extra_id=""):
    name_id = name+'_id'
    df[name_id] = df.index + number
    df[name_id] = name + "_" + df[name_id].astype(str) + extra_id
    return df

In [4]:
def tournament_names(folder='csv'):
    tournament_list = []
    for name in os.listdir(folder):
        path = os.path.join(folder, name)
        if os.path.isdir(path):
            tournament_list.append(name)
    return tournament_list

def region_by_id(touranment_name, region): #Esto puede estar mal, revisar como asigna el numero de region
    for _, row in region.iterrows():
        if row['region'].lower() in touranment_name.lower():
            return row['reg_id']
    return "reg_4"

#Team economy stats Esto no esta igual que round stats, hay que depurar que paso 
def sort_teams(team_string):
     split_teams= team_string.split("-",2)
     map_info = split_teams[-1]
     sorted_teams = sorted(split_teams[0:2],key=str.lower)
     return "-".join(sorted_teams)+"-"+map_info

In [5]:
#This should run only once.
#This should be create in another way, probably from a json 
region_name = ["americas","emea","china","pacific","global"]
region_id = ["reg_0","reg_1","reg_2","reg_3","reg_4",]

region_data = {"region":region_name,"reg_id":region_id}


df_region = pd.DataFrame(data=region_data)

tournaments = tournament_names('csv')
df_tournaments = pd.DataFrame(data=tournaments,columns=["tournament_name"])

In [6]:
df_tournaments["event"] = df_tournaments["tournament_name"].apply(lambda x: x.replace("_", " "))

df_tournaments['reg_id'] = df_tournaments['event'].apply(lambda x: region_by_id(x, df_region))

df_tournaments['tour_id'] = df_tournaments['tournament_name']

#text_to_index(df_tournaments,"tour")

df_tournaments = df_tournaments.drop(["tournament_name"], axis=1) #This drop is not ok, I should re organize this

df_region.to_csv(path_or_buf='tables/table_region.csv',index=False,encoding='iso-8859-1')
df_tournaments.to_csv(path_or_buf='tables/table_tournament.csv',index=False,encoding='iso-8859-1')

In [7]:
df_tournaments

                            event reg_id                         tour_id
0  valorant masters santiago 2026  reg_4  valorant_masters_santiago_2026
1       vct 2026 americas kickoff  reg_0       vct_2026_americas_kickoff
2       vct 2026 americas stage 1  reg_0       vct_2026_americas_stage_1
3          vct 2026 china kickoff  reg_2          vct_2026_china_kickoff
4          vct 2026 china stage 1  reg_2          vct_2026_china_stage_1
5           vct 2026 emea kickoff  reg_1           vct_2026_emea_kickoff
6           vct 2026 emea stage 1  reg_1           vct_2026_emea_stage_1
7        vct 2026 pacific kickoff  reg_3        vct_2026_pacific_kickoff
8        vct 2026 pacific stage 1  reg_3        vct_2026_pacific_stage_1

In [8]:
df_draft_concat = concat_csv_from_different_folders(folder="csv", prefix="draft_")
df_team = pd.DataFrame(df_draft_concat["team"].unique(), columns=["team"])

df_team["team_id"] = df_team["team"]

df_team = df_team.drop(["team"], axis=1) #Need to add full name of the team. 
#text_to_index(df_team,"team") This ids are not working for update

df_team.to_csv(path_or_buf='tables/table_teams.csv',index=False,encoding='iso-8859-1')

In [9]:
df_players_stats = concat_csv_from_different_folders(folder="csv", prefix="player_stats")
df_players = df_players_stats[['player','team']].drop_duplicates(subset=['player'],ignore_index=True)
df_players["player_id"] = df_players["team"]+"_"+df_players["player"]

#text_to_index(df_players,"player") This ids are not working for update

df_players_id = pd.merge(df_players, df_team[["team_id"]],how="left", left_on="team", right_on="team_id")

df_players_id = df_players_id.drop(["team"],axis=1)

#Le saco las regiones a los players ? 
#df_players_id = pd.merge(df_players_id, df_teams_concat[["team_id","region"]],how="left", left_on="team_id", right_on="team_id")

df_players_id.to_csv(path_or_buf='tables/table_players.csv',index=False,encoding='iso-8859-1')

In [21]:
def match_id_vlr(url):
    match = re.search(r"vlr\.gg/(\d+)", url)
    if match:
        vlr_id = match.group(1)
        return vlr_id


df_round_detail = concat_csv_from_different_folders(folder="csv", prefix="round_detail")

df_filter_map = df_round_detail["map"] != "all"
df_round_detail_filter = df_round_detail[df_filter_map]
df_round_detail_filter["event"] = df_round_detail_filter["event"].apply(lambda x: x.replace(":", "").lower())
df_round_detail_filter["vlr_id"] = df_round_detail_filter["source_url"].apply(
    match_id_vlr
)
df_round_detail_filter["vlr_id-map"] = (
    df_round_detail_filter["vlr_id"] + "-" + df_round_detail_filter["map"]
)

df_maps_id = pd.DataFrame(
    df_round_detail_filter["vlr_id-map"].unique(), columns=["vlr_id-map"]
)

#text_to_index(df_maps_id, "map")

df_maps_id["map_id"] = df_maps_id["vlr_id-map"]


df_maps_id[["vlr_id", "map"]] = df_maps_id["vlr_id-map"].str.rsplit(
    "-", n=1, expand=True
)

df_match_id = pd.DataFrame(data=df_maps_id["vlr_id"].unique(), columns=["vlr_id"])
text_to_index(df_match_id, "series")

df_round_detail_filter = pd.merge(
    df_round_detail_filter,
    df_tournaments[["event", "reg_id", "tour_id"]],
    how="left",
    left_on="event",
    right_on="event",
)

df_match_id = pd.merge(
    df_match_id,
    df_round_detail_filter[["vlr_id", "reg_id", "tour_id"]],
    how="left",
    left_on="vlr_id",
    right_on="vlr_id",
)

df_match_id.drop_duplicates(inplace=True, ignore_index=True)

df_maps_id = pd.merge(
    df_maps_id,
    df_match_id,
    how="left",
    left_on="vlr_id",
    right_on="vlr_id",
)

df_tournament_played_a = df_round_detail_filter[["teamA","event","reg_id","tour_id"]].copy()
df_tournament_played_b = df_round_detail_filter[["teamB","event","reg_id","tour_id"]].copy()
df_tournament_played_b.rename(columns={"teamB":"teamA"},inplace=True)
df_tournament_played = pd.concat([df_tournament_played_a,df_tournament_played_b],ignore_index=True)

df_tournament_played.drop_duplicates(inplace=True, ignore_index=True)

df_maps_id = df_maps_id.drop(["vlr_id-map","series_id"],axis=1)

df_maps_id = df_maps_id.rename(columns={"vlr_id":"series_id"})

df_maps_id.to_csv(path_or_buf='tables/table_maps_id.csv',index=False,encoding='iso-8859-1')

df_match_id= df_match_id.drop(["series_id"],axis=1)

df_match_id = df_match_id.rename(columns={"vlr_id":"series_id"})

df_match_id.to_csv(path_or_buf='tables/table_match_id.csv',index=False,encoding='iso-8859-1')

#df_round_detail_filter.to_csv(path_or_buf='tables/table_round_detail.csv',index=False,encoding='iso-8859-1') Esto hay que limpiar

df_tournament_played.to_csv(path_or_buf='tables/table_tournament_played.csv',index=False,encoding='iso-8859-1')

In [23]:
df_tournament_played[df_tournament_played["teamA"] == "LOUD"]

   teamA                      event reg_id                    tour_id
12  LOUD  vct 2026 americas kickoff  reg_0  vct_2026_americas_kickoff
95  LOUD  vct 2026 americas stage 1  reg_0  vct_2026_americas_stage_1

In [11]:
def match_id_vlr(url):
    match = re.search(r"vlr\.gg/(\d+)", url)
    if match:
        vlr_id = match.group(1)
        return vlr_id


df_round_detail = concat_csv_from_different_folders(folder="csv", prefix="round_detail")

df_filter_map = df_round_detail["map"] != "all"
df_round_detail_filter = df_round_detail[df_filter_map]
df_round_detail_filter["event"] = df_round_detail_filter["event"].apply(lambda x: x.replace(":", "").lower())
df_round_detail_filter["vlr_id"] = df_round_detail_filter["source_url"].apply(
    match_id_vlr
)
df_round_detail_filter["vlr_id-map"] = (
    df_round_detail_filter["vlr_id"] + "-" + df_round_detail_filter["map"]
)

df_maps_id = pd.DataFrame(
    df_round_detail_filter["vlr_id-map"].unique(), columns=["vlr_id-map"]
)

df_maps_id["map_id"] = df_maps_id["vlr_id-map"]

df_maps_id[["vlr_id", "map"]] = df_maps_id["vlr_id-map"].str.rsplit(
    "-", n=1, expand=True
)

df_match_id = pd.DataFrame(data=df_maps_id["vlr_id"].unique(), columns=["vlr_id"])

df_match_id["series_id"] = df_match_id["vlr_id"]

#text_to_index(df_match_id, "series")

df_round_detail_filter = pd.merge(
    df_round_detail_filter,
    df_tournaments[["event", "reg_id", "tour_id"]],
    how="left",
    left_on="event",
    right_on="event",
)

df_match_id = pd.merge(
    df_match_id,
    df_round_detail_filter[["vlr_id", "reg_id", "tour_id"]],
    how="left",
    left_on="vlr_id",
    right_on="vlr_id",
)

df_match_id.drop_duplicates(inplace=True, ignore_index=True)

df_maps_id = pd.merge(
    df_maps_id,
    df_match_id,
    how="left",
    left_on="vlr_id",
    right_on="vlr_id",
)

df_tournament_played = df_round_detail_filter[["teamA","event","reg_id","tour_id"]].copy()
df_tournament_played.drop_duplicates(inplace=True, ignore_index=True)

df_maps_id = df_maps_id.drop(["vlr_id-map","vlr_id"], axis=1)

df_maps_id.to_csv(path_or_buf='tables/table_maps_id.csv',index=False,encoding='iso-8859-1')

df_match_id = df_match_id.drop(["vlr_id"], axis=1)

df_match_id.to_csv(path_or_buf='tables/table_match_id.csv',index=False,encoding='iso-8859-1')

#df_round_detail_filter.to_csv(path_or_buf='tables/table_round_detail.csv',index=False,encoding='iso-8859-1') Esto hay que limpiar

df_tournament_played.to_csv(path_or_buf='tables/table_tournament_played.csv',index=False,encoding='iso-8859-1')

In [12]:
#Player performance
df_player_performance = concat_csv_from_different_folders(folder="csv",prefix="player_performance")

df_filter_map = df_player_performance["map"] != "all"
df_player_performance = df_player_performance[df_filter_map]
df_player_performance["series_id"] = df_player_performance["source_url"].apply(
    match_id_vlr
)
df_player_performance["map_id"] = (
    df_player_performance["series_id"] + "-" + df_player_performance["map"]
    )

df_player_performance = pd.merge(df_player_performance, df_maps_id[["map_id","reg_id","tour_id"]],how="left", left_on="map_id", right_on="map_id")

#df_player_performance = df_player_performance.drop(["vlr_id-map","vlr_id"], axis=1)

df_player_performance.to_csv(path_or_buf='tables/table_player_performance.csv',index=False,encoding='iso-8859-1')

In [13]:
#player stats

df_player_stats = concat_csv_from_different_folders(folder="csv", prefix="player_stats")

df_filter_map = df_player_stats["map"] != "all"
df_player_stats = df_player_stats[df_filter_map]
df_player_stats["series_id"] = df_player_stats["source_url"].apply(
    match_id_vlr
)
df_player_stats["map_id"] = (
    df_player_stats["series_id"] + "-" + df_player_stats["map"]
)

df_player_stats = pd.merge(df_player_stats, df_maps_id[["map_id","reg_id","tour_id"]],how="left", left_on="map_id", right_on="map_id")

df_player_stats_types = df_player_stats.astype(
    {
        "acsBoth": int,
        "acsT": int,
        "acsCT": int,
        "killsBoth": int,
        "killsT": int,
        "killsCT": int,
        "deadBoth": int,
        "deadT": int,
        "deadCT": int,
        "assistsBoth":int,
        "assistsT":int,
        "assistsCT":int,
        "k-dBoth":int,
        "k-dT":int,
        "k-dCT":int,
        "adrBoth":int,
        "adrT":int,
        "adrCT":int,
        "fkBoth":int,
        "fkT":int,
        "fkCT":int,
        "fdBoth":int,
        "fdT":int,
        "fdCT":int,
        "fk-fdBoth":int,
        "fk-fdT":int,
        "fk-fdCT":int,
    }
)

df_player_stats_types.to_csv(path_or_buf='tables/table_player_stats.csv',index=False,encoding='iso-8859-1')

In [14]:
df_draft_concat = concat_csv_from_different_folders(folder="csv", prefix="draft_")
df_draft_concat["match_instance"] = df_draft_concat["source_url"].apply(
    lambda x : x[-3:].lstrip("-")
)
df_draft_concat["series_id"] = df_draft_concat["source_url"].apply(match_id_vlr)

df_draft_concat = pd.merge(
    df_draft_concat,
    df_maps_id[["series_id","reg_id", "tour_id"]],
    how="left",
    left_on="series_id",
    right_on="series_id",
)
df_draft_concat_filter = df_draft_concat["order"] == "A"
df_draft_concat = df_draft_concat[df_draft_concat_filter]
df_draft_concat.drop_duplicates(inplace=True, ignore_index=True)

# ACA AGREGAR LO DE LA COMPO 

df_draft_concat.to_csv(path_or_buf='tables/table_draft.csv',index=False,encoding='iso-8859-1')

In [15]:
# round stats

df_round_concat = concat_csv_from_different_folders(folder="csv", prefix="round_detail")

# table with the maps force the maps I should add new maps manually 
map_info = {
    "map": [
        "Haven",
        "Pearl",
        "Abyss",
        "Split",
        "Corrode",
        "Breeze",
        "Bind",
        "Ascent",
        "Fracture",
        "Icebox",
        "Lotus",
        "Sunset",
    ], "image_path": []
}
map_info["image_path"] = [f"maps/{nombre.lower()}.png" for nombre in map_info["map"]]

df_maps_name_id = pd.DataFrame(map_info)

text_to_index(df_maps_name_id, "map")

df_maps_name_id.to_csv(
    path_or_buf="tables/table_maps_name_id.csv", index=False, encoding="iso-8859-1"
)

df_round_concat["series_id"] = df_round_concat["source_url"].apply(match_id_vlr)
df_round_concat["map_id"] = df_round_concat["series_id"] + "-" + df_round_concat["map"]

df_round_concat = pd.merge(
    df_round_concat,
    df_maps_id[["map_id", "reg_id", "tour_id"]],
    how="left",
    left_on="map_id",
    right_on="map_id",
)

# df_round_concat["remove_duplicate"] = df_round_concat["map_id"]+"-"+df_round_concat["round"].astype(str)

# df_test_round = df_round_concat.copy()

df_round_concat = df_round_concat.drop_duplicates(subset=["map_id", "round"])

# df_round_concat = df_round_concat.drop("remove_duplicate",axis=1)

df_round_concat["team_map_round_id"] = (
    df_round_concat["teamA"]
    + "-"
    + df_round_concat["teamB"]
    + "-"
    + df_round_concat["map_id"]
    + "-"
    + df_round_concat["round"].astype(str)
)

df_round_concat["team_map_round_id"] = df_round_concat["team_map_round_id"].apply(
    sort_teams
)

df_round_concat.to_csv(
    path_or_buf="tables/table_round_info.csv", index=False, encoding="iso-8859-1"
)

In [16]:
df_team_economy = concat_csv_from_different_folders(folder="csv", prefix="team_economy")

columns_update = ["team_a_economy","team_b_economy","team_a_bank","team_b_bank"]

for column_name in columns_update:
     df_team_economy[column_name] = df_team_economy[column_name].apply(convert_k)

df_team_economy["series_id"] = df_team_economy["source_url"].apply(
    match_id_vlr
)
df_team_economy["map_id"] = (
    df_team_economy["series_id"] + "-" + df_team_economy["map"]
)

df_team_economy = pd.merge(df_team_economy, df_maps_id[["map_id","reg_id","tour_id"]],how="left", left_on="map_id", right_on="map_id")

df_team_economy["team_map_round_id"] = df_team_economy["team_a"]+"-"+df_team_economy["team_b"]+"-"+df_team_economy["map_id"]+"-"+df_team_economy["round"].astype(str)

df_team_economy["team_map_round_id"] = df_team_economy["team_map_round_id"].apply(sort_teams)

df_team_economy = df_team_economy[df_team_economy["reg_id"] != "reg_2"]

df_team_economy = pd.merge(df_team_economy,df_round_concat[["teamA","teamB","rndA","rndB","team_map_round_id","winCon","side"]],how="left",left_on="team_map_round_id",right_on="team_map_round_id")
df_team_economy["side_b"] = np.where(df_team_economy["side"]=="atk","def","atk")
df_team_economy["eco_side"] = np.where(df_team_economy["team_a"] == df_team_economy["teamA"],df_team_economy["side"],df_team_economy["side_b"] )
df_team_economy["eco_win_A"] = np.where(df_team_economy["team_a"] == df_team_economy["teamA"],df_team_economy["rndA"],df_team_economy["rndB"] )
df_team_economy = df_team_economy.drop(columns=["teamA","teamB","rndA","rndB","side","side_b"],axis=1)
df_team_economy = df_team_economy.rename(columns={"eco_side":"side","eco_win_A":"win_A"})
df_team_economy

df_team_economy.to_csv(path_or_buf='tables/table_team_economy.csv',index=False,encoding='iso-8859-1') #No china, sometimes vlr dont have the data on china

In [ ]:
#Hasta arriba

In [32]:
# Agent names and urls

agent_path_name = [
    "astra.png",
    "breach.png",
    "brimstone.png",
    "chamber.png",
    "clove.png",
    "cypher.png",
    "deadlock.png",
    "fade.png",
    "gekko.png",
    "harbor.png",
    "iso.png",
    "jett.png",
    "kayo.png",
    "killjoy.png",
    "miks.png",
    "neon.png",
    "omen.png",
    "phoenix.png",
    "raze.png",
    "reyna.png",
    "sage.png",
    "skye.png",
    "sova.png",
    "tejo.png",
    "veto.png",
    "viper.png",
    "vyse.png",
    "waylay.png",
    "yoru.png",
]

agent_info = {"agent_name": [], "agent_path": []}

agent_info["agent_name"] = [f"{agent.split('.')[0].capitalize()}" for agent in agent_path_name]
agent_info["agent_path"] = [f"agents/{path.lower()}" for path in agent_path_name]

df_agent_info = pd.DataFrame(agent_info)

df_agent_info.to_csv(
    path_or_buf="tables/table_agent_info.csv", index=False, encoding="iso-8859-1"
)

In [47]:
for agent in agent_path_name:
    print(agent.split(".")[0].capitalize())

Astra
Breach
Brimstone
Chamber
Clove
Cypher
Deadlock
Fade
Gekko
Harbor
Iso
Jett
Kayo
Killjoy
Miks
Neon
Omen
Phoenix
Raze
Reyna
Sage
Skye
Sova
Tejo
Veto
Viper
Vyse
Waylay
Yoru

In [33]:
df_compos = df_player_stats[['team','player', 'agent','map','date', 'source_url', 'event', 'series_id', 'map_id', 'reg_id','tour_id']].copy()

In [44]:
teams = list(df_compos.team.unique())
maps_to_test = list(df_compos.map_id.unique())

In [46]:
t1 = teams[0]

In [49]:
df_compos.query("team == @t1")

,team,player,agent,map,date,source_url,event,series_id,map_id,reg_id,tour_id
0,M8,Minny,Cypher,Haven,2026-02-28 12:00:00,https://www.vlr.gg/625788/gentle-mates-vs-edwa...,Valorant Masters Santiago 2026,625788,625788-Haven,reg_4,valorant_masters_santiago_2026
1,M8,starxo,Sova,Haven,2026-02-28 12:00:00,https://www.vlr.gg/625788/gentle-mates-vs-edwa...,Valorant Masters Santiago 2026,625788,625788-Haven,reg_4,valorant_masters_santiago_2026
2,M8,marteen,Yoru,Haven,2026-02-28 12:00:00,https://www.vlr.gg/625788/gentle-mates-vs-edwa...,Valorant Masters Santiago 2026,625788,625788-Haven,reg_4,valorant_masters_santiago_2026
3,M8,bipo,Neon,Haven,2026-02-28 12:00:00,https://www.vlr.gg/625788/gentle-mates-vs-edwa...,Valorant Masters Santiago 2026,625788,625788-Haven,reg_4,valorant_masters_santiago_2026
4,M8,GLYPH,Astra,Haven,2026-02-28 12:00:00,https://www.vlr.gg/625788/gentle-mates-vs-edwa...,Valorant Masters Santiago 2026,625788,625788-Haven,reg_4,valorant_masters_santiago_2026
...,...,...,...,...,...,...,...,...,...,...,...
2110,M8,Minny,Cypher,Haven,2026-02-14 11:10:00,https://www.vlr.gg/594760/gentle-mates-vs-fnat...,VCT 2026: EMEA Kickoff,594760,594760-Haven,reg_1,vct_2026_emea_kickoff
2111,M8,marteen,Yoru,Haven,2026-02-14 11:10:00,https://www.vlr.gg/594760/gentle-mates-vs-fnat...,VCT 2026: EMEA Kickoff,594760,594760-Haven,reg_1,vct_2026_emea_kickoff
2112,M8,starxo,Sova,Haven,2026-02-14 11:10:00,https://www.vlr.gg/594760/gentle-mates-vs-fnat...,VCT 2026: EMEA Kickoff,594760,594760-Haven,reg_1,vct_2026_emea_kickoff
2113,M8,bipo,Neon,Haven,2026-02-14 11:10:00,https://www.vlr.gg/594760/gentle-mates-vs-fnat...,VCT 2026: EMEA Kickoff,594760,594760-Haven,reg_1,vct_2026_emea_kickoff
2114,M8,GLYPH,Astra,Haven,2026-02-14 11:10:00,https://www.vlr.gg/594760/gentle-mates-vs-fnat...,VCT 2026: EMEA Kickoff,594760,594760-Haven,reg_1,vct_2026_emea_kickoff

In [79]:
set_economy = set(df_team_economy["team_map_round_id"])
set_round = set(df_round_concat["team_map_round_id"])

print(f"IDs en Economy que no están en Round: {len(set_economy - set_round)}")
print(f"IDs en Round que no están en Economy: {len(set_round - set_economy)}")

IDs en Economy que no están en Round: 0
IDs en Round que no están en Economy: 1748

In [ ]:
#draft (raro hay que revisar)
#Creo que ya no lo uso mas 
# df_draft_concat = concat_csv_from_different_folders(folder="csv", prefix="draft_")
# df_draft_concat["match_instance"] = df_draft_concat["source_url"].apply(
#     lambda x : x[-3:].lstrip("-")
# )
# df_draft_concat["vlr_id"] = df_draft_concat["source_url"].apply(match_id_vlr)

# df_draft_concat = pd.merge(
#     df_draft_concat,
#     df_maps_id[["vlr_id", "series_id", "reg_id", "tour_id"]],
#     how="left",
#     left_on="vlr_id",
#     right_on="vlr_id",
# )
# df_draft_concat.drop_duplicates(inplace=True, ignore_index=True)

# df_draft_concat_fix = create_draft_table(df_draft_concat)

# df_draft_concat_fix['1st_ban'] = df_draft_concat_fix.apply(first_ban,axis=1)

# df_draft_concat_fix['2nd_ban'] = df_draft_concat_fix.apply(second_ban,axis=1)

# df_draft_concat_fix['1st_pick'] = df_draft_concat_fix.apply(first_pick, axis=1)

# df_draft_concat_fix['2nd_pick'] = df_draft_concat_fix.apply(second_pick,axis=1)

# df_draft_concat_fix['decider'] = df_draft_concat_fix.apply(decider_pick,axis=1)

# df_draft_concat_fix.to_csv(path_or_buf='tables/table_draft.csv',index=False,encoding='iso-8859-1')

In [133]:
df_player_performance.describe()

,2K,3K,4K,5K,1v1,1v2,1v3,1v4,1v5,ECON,PL,DE
count,3680.000000,3680.000000,3680.000000,3680.000000,3680.000000,3680.000000,3680.000000,3680.000000,3680.000000,3680.000000,3680.000000,3680.000000
mean,2.623641,0.788859,0.166033,0.019022,0.204348,0.111141,0.027174,0.003804,0.000272,51.713587,1.470652,0.437772
std,1.645188,0.921924,0.415634,0.136620,0.457587,0.330370,0.165921,0.061570,0.016485,16.289112,1.845694,0.690822
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,41.000000,0.000000,0.000000
50%,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,1.000000,0.000000
75%,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,61.000000,2.000000,1.000000
max,11.000000,5.000000,3.000000,1.000000,3.000000,3.000000,2.000000,1.000000,1.000000,180.000000,11.000000,5.000000

In [16]:
df_player_stats[df_player_stats["ratingT"] > 4]

,team,player,agent,ratingBoth,ratingT,rating-ct,acsBoth,acsT,acsCT,killsBoth,...,fdCT,fk-fdBoth,fk-fdT,fk-fdCT,map,date,event,date-map,map_id,series_id
1991,NAVI,koalanoob,Raze,1.75,4.07,1.56,359.0,683.0,333.0,16.0,...,0.0,5.0,1.0,1.0,Split,2025-04-09 13:15:00,VCT 2025: EMEA Stage 1,2025-04-09 13:15:00-Split,map_304,series_121

In [ ]:
import json